on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job to test Actions
    steps:
      - name: hello world
        run: echo "Hello world Actions!"
      - run: pwd
  container_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
      - run: echo "Inside docker."
      - name: Download codes
        uses: actions/checkout@v2
      - run: ls -l && pwd
      - run: export PYTHONPATH="ABCDE"
      - run: echo $PYTHONPATH
