on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job to test Actions
    steps:
      - name: hello world
        run: echo "Hello world Actions!"
  container_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
      - run: echo "Inside docker."
