on: [push]
defaults:
  QQ: ABC
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job to test Actions
    steps:
      - name: hello world
        run: echo "Hello world Actions!"
      - run: pwd
      - uses: actions/upload-artifact@v2
        with:
          name: QQ1
          path: ${{QQ}}/*
  container_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    needs: hello_world_job
    steps:
      - run: echo "Inside docker."
      - name: Download codes
        uses: actions/checkout@v2
      - run: ls -l && pwd
      - run: export PYTHONPATH="ABCDE"
      - run: echo $PYTHONPATH
