on: [push]
jobs:
  build_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.OWNER }}
          password: ${{ secrets.PAT }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build deps
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/darelbeida-org/test_debian10_gnu:latest
          target: first_stage
          cache-from: type=registry,ref=ghcr.io/darelbeida-org/test_debian10_gnu:latest
          cache-to: type=inline

      - name: Build runtime
        id: docker_build_runtime
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/darelbeida-org/test_debian10_gnu_runtime:latest
          target: second_stage
          cache-from: type=registry,ref=ghcr.io/darelbeida-org/test_debian10_gnu:latest
          cache-to: type=inline
